// ============ BOTHIES (MBA-maintained, sourced from Wikipedia/MBA as of March 2025) ============
var BOTHIES = [
  {id:"b001",name:"Achnanclach",lat:58.427,lng:-4.346,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/achnanclach/"},
  {id:"b002",name:"Coiremor, Magoo's Bothy",lat:57.857,lng:-4.858,region:"Northern Highlands",district:"Ross-shire",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/coiremor-choire-mhoir/"},
  {id:"b003",name:"Croft House, Lochstrathy",lat:58.412,lng:-4.067,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/croft-house-lochstrathy/"},
  {id:"b004",name:"Glencoul",lat:58.228,lng:-4.947,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/glencoul/"},
  {id:"b005",name:"Glendhu",lat:58.259,lng:-4.928,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/glendhu/"},
  {id:"b006",name:"Kearvaig",lat:58.609,lng:-4.941,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/kearvaig/"},
  {id:"b007",name:"Knockdamph",lat:57.915,lng:-4.895,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/knockdamph/"},
  {id:"b008",name:"Schoolhouse, Duag Bridge",lat:57.935,lng:-4.805,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/schoolhouse-duag-bridge/"},
  {id:"b009",name:"Shenavall",lat:57.777,lng:-5.254,region:"Northern Highlands",district:"Wester Ross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/shenavall/"},
  {id:"b010",name:"Strabeg",lat:58.425,lng:-4.756,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/strabeg/"},
  {id:"b011",name:"Strathan",lat:58.503,lng:-5.01,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/strathan/"},
  {id:"b012",name:"Strathchailleach",lat:58.545,lng:-5.01,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/strathchailleach/"},
  {id:"b013",name:"Suileag",lat:58.14,lng:-5.145,region:"Northern Highlands",district:"Sutherland",mbaUrl:"https://www.mountainbothies.org.uk/bothies/northern-highlands/suileag/"},
  {id:"b014",name:"Bearnais",lat:57.434,lng:-5.298,region:"North West Highlands and Islands",district:"Wester Ross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/bearnais/"},
  {id:"b015",name:"Camasunary",lat:57.19,lng:-6.112,region:"North West Highlands and Islands",district:"Skye",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/camasunary/"},
  {id:"b016",name:"Camban",lat:57.214,lng:-5.225,region:"North West Highlands and Islands",district:"Kintail",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/camban/"},
  {id:"b017",name:"Coire Fionnaraich",lat:57.476,lng:-5.421,region:"North West Highlands and Islands",district:"Wester Ross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/coire-fionnaraich/"},
  {id:"b018",name:"Craig",lat:57.61,lng:-5.727,region:"North West Highlands and Islands",district:"Wester Ross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/craig/"},
  {id:"b019",name:"Easan Dorcha (The Teahouse)",lat:57.519,lng:-5.323,region:"North West Highlands and Islands",district:"Wester Ross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/easan-dorcha-the-teahouse/"},
  {id:"b020",name:"Lookout (Rubha Hunish)",lat:57.701,lng:-6.344,region:"North West Highlands and Islands",district:"Skye",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/lookout-rubha-hunish/"},
  {id:"b021",name:"Maol Bhuidhe",lat:57.372,lng:-5.241,region:"North West Highlands and Islands",district:"Wester Ross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/maol-bhuidhe/"},
  {id:"b022",name:"Ollisdal",lat:57.36,lng:-6.636,region:"North West Highlands and Islands",district:"Skye",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/ollisdal/"},
  {id:"b023",name:"Taigh Thormoid Dhuibh (Raasay)",lat:57.499,lng:-5.988,region:"North West Highlands and Islands",district:"Skye",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/taigh-thormoid-dhuibh-raasay/"},
  {id:"b024",name:"Uags",lat:57.349,lng:-5.787,region:"North West Highlands and Islands",district:"Applecross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/uags/"},
  {id:"b025",name:"Uisinis",lat:57.28,lng:-7.231,region:"North West Highlands and Islands",district:"Outer Hebrides",mbaUrl:"https://www.mountainbothies.org.uk/bothies/north-west-highlands-islands/uisinis/"},
  {id:"b026",name:"A' Chuil",lat:56.977,lng:-5.384,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/achuil/"},
  {id:"b027",name:"Dibidil",lat:56.952,lng:-6.289,region:"Western Highlands",district:"R\u00f9m",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/dibidil/"},
  {id:"b028",name:"Gleann Dubh-lighe",lat:56.884,lng:-5.375,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/gleann-dubh-lighe/"},
  {id:"b029",name:"Glenpean",lat:56.958,lng:-5.396,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/glenpean/"},
  {id:"b030",name:"Guirdil",lat:57.025,lng:-6.418,region:"Western Highlands",district:"R\u00f9m",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/guirdil/"},
  {id:"b031",name:"Invermallie",lat:56.953,lng:-5.067,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/invermallie/"},
  {id:"b032",name:"Kinbreack",lat:57.013,lng:-5.292,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/kinbreack/"},
  {id:"b033",name:"Oban",lat:56.952,lng:-5.515,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/oban/"},
  {id:"b034",name:"Sourlies",lat:56.997,lng:-5.513,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/sourlies/"},
  {id:"b035",name:"Suardalan",lat:57.197,lng:-5.506,region:"Western Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/western-highlands-islands/suardalan/"},
  {id:"b036",name:"Abyssinia",lat:56.266,lng:-4.818,region:"Southwest Highlands and Islands",district:"Loch Lomond",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/abyssinia/"},
  {id:"b037",name:"Cadderlie",lat:56.486,lng:-5.175,region:"Southwest Highlands and Islands",district:"North Argyll",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/cadderlie/"},
  {id:"b038",name:"Carron",lat:56.145,lng:-5.311,region:"Southwest Highlands and Islands",district:"Knapdale",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/carron/"},
  {id:"b039",name:"Cruib",lat:55.977,lng:-5.902,region:"Southwest Highlands and Islands",district:"Jura",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/cruib/"},
  {id:"b040",name:"Doune Byre",lat:56.293,lng:-4.696,region:"Southwest Highlands and Islands",district:"Loch Lomond",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/doune-byre/"},
  {id:"b041",name:"Druimnashallog",lat:56.294,lng:-5.396,region:"Southwest Highlands and Islands",district:"Lorne",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/druimnashallag/"},
  {id:"b042",name:"Essan",lat:56.875,lng:-5.584,region:"Southwest Highlands and Islands",district:"Wester Ross",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/essan/"},
  {id:"b043",name:"Glengarrisdale",lat:56.107,lng:-5.79,region:"Southwest Highlands and Islands",district:"Jura",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/glengarrisdale/"},
  {id:"b044",name:"Leacraithnaich",lat:56.562,lng:-5.676,region:"Southwest Highlands and Islands",district:"Ardgour",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/leacraithnaich/"},
  {id:"b045",name:"Mark Cottage",lat:56.116,lng:-4.849,region:"Southwest Highlands and Islands",district:"Loch Lomond",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/mark-cottage/"},
  {id:"b046",name:"Resourie",lat:56.781,lng:-5.502,region:"Southwest Highlands and Islands",district:"Ardgour",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/resourie/"},
  {id:"b047",name:"Rowchoish",lat:56.202,lng:-4.684,region:"Southwest Highlands and Islands",district:"Loch Lomond",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/rowchoish/"},
  {id:"b048",name:"Taigh Seumas a' Ghlinne, Glen Duror",lat:56.635,lng:-5.227,region:"Southwest Highlands and Islands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/taigh-seumas-a-ghlinne-glenduror/"},
  {id:"b049",name:"Tomsleibhe",lat:56.466,lng:-5.869,region:"Southwest Highlands and Islands",district:"Mull",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southwest-highlands-islands/tomsleibhe/"},
  {id:"b050",name:"Achadh-nan-darach",lat:57.112,lng:-4.787,region:"Central Highlands",district:"Fort Augustus",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/achadh-nan-darach/"},
  {id:"b051",name:"Ben Alder Cottage",lat:56.779,lng:-4.459,region:"Central Highlands",district:"Rannoch",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/ben-alder-cottage/"},
  {id:"b052",name:"Blackburn of Corrieyairack",lat:57.088,lng:-4.672,region:"Central Highlands",district:"Monadhliath",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/blackburn-of-corrieyairack/"},
  {id:"b053",name:"Culra",lat:56.854,lng:-4.424,region:"Central Highlands",district:"Rannoch",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/culra/",closed:true},
  {id:"b054",name:"Glenbuck",lat:57.057,lng:-4.746,region:"Central Highlands",district:"Monadhliath",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/glenbuck/"},
  {id:"b055",name:"Gorton",lat:56.597,lng:-4.649,region:"Central Highlands",district:"Rannoch",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/gorton/"},
  {id:"b056",name:"Lairig Leacach",lat:56.823,lng:-4.816,region:"Central Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/lairig-leacach/"},
  {id:"b057",name:"Loch Chiarain",lat:56.731,lng:-4.798,region:"Central Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/loch-chiarain/"},
  {id:"b058",name:"Luib Chonnal",lat:57.006,lng:-4.646,region:"Central Highlands",district:"Monadhliath",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/luib-chonnal/"},
  {id:"b059",name:"Meanach",lat:56.775,lng:-4.839,region:"Central Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/meanach/"},
  {id:"b060",name:"Staoineag",lat:56.771,lng:-4.791,region:"Central Highlands",district:"Lochaber",mbaUrl:"https://www.mountainbothies.org.uk/bothies/central-highlands/staoineag/"},
  {id:"b061",name:"Allt Scheicheachan",lat:56.84,lng:-3.912,region:"Eastern Highlands",district:"Badenoch",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/allt-scheicheachan/"},
  {id:"b062",name:"Callater Stable",lat:56.944,lng:-3.353,region:"Eastern Highlands",district:"Mounth",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/callater-stable/"},
  {id:"b063",name:"Charr",lat:56.938,lng:-2.633,region:"Eastern Highlands",district:"Mounth",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/charr/"},
  {id:"b064",name:"Corrour",lat:57.042,lng:-3.681,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/corrour/"},
  {id:"b065",name:"Faindouran",lat:57.137,lng:-3.519,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/faindouran/"},
  {id:"b066",name:"Fords of Avon Refuge Hut",lat:57.11,lng:-3.584,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/fords-of-avon-refuge/",closed:true},
  {id:"b067",name:"Garbh Choire Refuge",lat:57.067,lng:-3.718,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/garbh-choire-refuge/",closed:true},
  {id:"b068",name:"Gelder Shiel Stable",lat:56.995,lng:-3.224,region:"Eastern Highlands",district:"Mounth",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/gelder-shiel-stable/"},
  {id:"b069",name:"Glas Allt Shiel Bothy",lat:56.927,lng:-3.191,region:"Eastern Highlands",district:"Loch Muick",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/glas-allt-shiel/"},
  {id:"b070",name:"Hutchison Memorial Hut",lat:57.078,lng:-3.613,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/hutchison-memorial-hut/"},
  {id:"b071",name:"Ruigh Aiteachain",lat:57.012,lng:-3.9,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/ruigh-aiteachain/"},
  {id:"b072",name:"Ruighe Ealasaid (Red House)",lat:56.962,lng:-3.643,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/ruighe-ealasaid-red-house/"},
  {id:"b073",name:"Ryvoan",lat:57.184,lng:-3.646,region:"Eastern Highlands",district:"Cairngorms",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/ryvoan/"},
  {id:"b074",name:"Shielin of Mark",lat:56.93,lng:-3.092,region:"Eastern Highlands",district:"Mounth",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/shielin-of-mark/"},
  {id:"b075",name:"Tarf Hotel (Feith Uaine)",lat:56.889,lng:-3.763,region:"Eastern Highlands",district:"Badenoch",mbaUrl:"https://www.mountainbothies.org.uk/bothies/eastern-highlands/tarf-hotel-feith-uaine/"},
  {id:"b076",name:"Brattleburn",lat:55.346,lng:-3.554,region:"Southern Scotland",district:"Lowther Hills",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/brattleburn/"},
  {id:"b077",name:"Burleywhag",lat:55.284,lng:-3.622,region:"Southern Scotland",district:"Lowther Hills",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/burleywhag/"},
  {id:"b078",name:"Clennoch",lat:55.276,lng:-4.201,region:"Southern Scotland",district:"Galloway",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/clennoch/"},
  {id:"b079",name:"Dryfehead",lat:55.286,lng:-3.308,region:"Southern Scotland",district:"Dumfriesshire",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/dryfehead/"},
  {id:"b080",name:"Gameshope",lat:55.453,lng:-3.371,region:"Southern Scotland",district:"Dumfriesshire",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/gameshope/"},
  {id:"b081",name:"Greensykes",lat:55.29,lng:-3.084,region:"Southern Scotland",district:"Dumfriesshire",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/greensykes/"},
  {id:"b082",name:"Kettleton Byre",lat:55.301,lng:-3.716,region:"Southern Scotland",district:"Lowther Hills",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/kettleton-byre/"},
  {id:"b083",name:"Leysburnfoot (Will's Bothy)",lat:55.272,lng:-2.732,region:"Southern Scotland",district:"Liddesdale",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/leysburnfoot-wills-bothy/"},
  {id:"b084",name:"Over Phawhope",lat:55.361,lng:-3.293,region:"Southern Scotland",district:"Dumfriesshire",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/over-phawhope/"},
  {id:"b085",name:"Tunskeen",lat:55.184,lng:-4.476,region:"Southern Scotland",district:"Galloway",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/tunskeen/"},
  {id:"b086",name:"White Laggan",lat:55.068,lng:-4.403,region:"Southern Scotland",district:"Galloway",mbaUrl:"https://www.mountainbothies.org.uk/bothies/southern-scotland/white-laggan/"}
                                          ];
